# Generated by Django 3.0.5 on 2020-06-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Imagen'),
        ),
    ]
