# Generated by Django 3.0.5 on 2020-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='avatar',
        ),
        migrations.AddField(
            model_name='empleado',
            name='full_nmae',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Imagen'),
        ),
    ]
