# Generated by Django 3.0.5 on 2020-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20200626_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='image',
        ),
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
